### ISSUE TITLE
multiple errors encountered while building under ubuntu 12.04

### ISSUE THREAD

**Issue by unclejack** [christianparpart/x0#48]
The current master fails to build on Ubuntu 12.04 with _clang-3.1 and clang-3.0 - wrong, it was LLVM 3.0 and LLVM 3.1_  with the following errors:

```
/home/unclejack/code/x0/lib/base/Socket.cpp: In member function ‘virtual ssize_t x0::Socket::read(x0::Buffer&)’:
/home/unclejack/code/x0/lib/base/Socket.cpp:330:81: error: no matching function for call to ‘max(long unsigned int, std::size_t)’
/home/unclejack/code/x0/lib/base/Socket.cpp:330:81: note: candidates are:
/usr/include/c++/4.6/bits/stl_algobase.h:210:5: note: template<class _Tp> const _Tp& std::max(const _Tp&, const _Tp&)
/usr/include/c++/4.6/bits/stl_algobase.h:254:5: note: template<class _Tp, class _Compare> const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
```

Fixing this with a manual typecast for the second argument leads us to the next error:

```
/home/unclejack/code/x0/lib/base/TimeSpan.cpp:15:34: error: call of overloaded ‘TimeSpan(long unsigned int)’ is ambiguous
/home/unclejack/code/x0/lib/base/TimeSpan.cpp:15:34: note: candidates are:
/home/unclejack/code/x0/include/x0/TimeSpan.h:28:2: note: x0::TimeSpan::TimeSpan(const x0::TimeSpan&)
/home/unclejack/code/x0/include/x0/TimeSpan.h:27:2: note: x0::TimeSpan::TimeSpan(std::size_t)
/home/unclejack/code/x0/include/x0/TimeSpan.h:26:2: note: x0::TimeSpan::TimeSpan(ev_tstamp)
```

Fixing this with a typecast generates new errors later on:

```
/home/unclejack/code/x0/lib/http/HttpCore.cpp: In member function ‘void x0::HttpCore::sys_now(x0::HttpRequest*, const FlowParams&, x0::FlowValue&)’:
/home/unclejack/code/x0/lib/http/HttpCore.cpp:462:73: error: call of overloaded ‘set(uint64_t)’ is ambiguous
/home/unclejack/code/x0/lib/http/HttpCore.cpp:462:73: note: candidates are:
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:216:19: note: x0::FlowValue& x0::FlowValue::set(bool)
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:224:19: note: x0::FlowValue& x0::FlowValue::set(int)
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:75:13: note: x0::FlowValue& x0::FlowValue::set(unsigned int)
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:232:19: note: x0::FlowValue& x0::FlowValue::set(long int)
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:77:13: note: x0::FlowValue& x0::FlowValue::set(long unsigned int)
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:240:19: note: x0::FlowValue& x0::FlowValue::set(long long int)
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:248:19: note: x0::FlowValue& x0::FlowValue::set(const x0::RegExp*) <near match>
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:248:19: note:   no known conversion for argument 1 from ‘uint64_t {aka long long unsigned int}’ to ‘const x0::RegExp*’
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:256:19: note: x0::FlowValue& x0::FlowValue::set(const x0::IPAddress*) <near match>
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:256:19: note:   no known conversion for argument 1 from ‘uint64_t {aka long long unsigned int}’ to ‘const x0::IPAddress*’
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:264:19: note: x0::FlowValue& x0::FlowValue::set(const char*) <near match>
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:264:19: note:   no known conversion for argument 1 from ‘uint64_t {aka long long unsigned int}’ to ‘const char*’
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:290:19: note: x0::FlowValue& x0::FlowValue::set(const x0::FlowValue&)
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:299:19: note: x0::FlowValue& x0::FlowValue::set(const x0::FlowArray*) <near match>
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:299:19: note:   no known conversion for argument 1 from ‘uint64_t {aka long long unsigned int}’ to ‘const x0::FlowArray*’
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:307:19: note: x0::FlowValue& x0::FlowValue::set(x0::FlowValue::Function) <near match>
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:307:19: note:   no known conversion for argument 1 from ‘uint64_t {aka long long unsigned int}’ to ‘x0::FlowValue::Function {aka bool (*)(void*)}’
/home/unclejack/code/x0/lib/http/HttpCore.cpp: In member function ‘void x0::HttpCore::phys_mtime(x0::HttpRequest*, const FlowParams&, x0::FlowValue&)’:
/home/unclejack/code/x0/lib/http/HttpCore.cpp:787:76: error: call of overloaded ‘set(uint64_t)’ is ambiguous
/home/unclejack/code/x0/lib/http/HttpCore.cpp:787:76: note: candidates are:
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:216:19: note: x0::FlowValue& x0::FlowValue::set(bool)
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:224:19: note: x0::FlowValue& x0::FlowValue::set(int)
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:75:13: note: x0::FlowValue& x0::FlowValue::set(unsigned int)
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:232:19: note: x0::FlowValue& x0::FlowValue::set(long int)
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:77:13: note: x0::FlowValue& x0::FlowValue::set(long unsigned int)
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:240:19: note: x0::FlowValue& x0::FlowValue::set(long long int)
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:248:19: note: x0::FlowValue& x0::FlowValue::set(const x0::RegExp*) <near match>
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:248:19: note:   no known conversion for argument 1 from ‘uint64_t {aka long long unsigned int}’ to ‘const x0::RegExp*’
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:256:19: note: x0::FlowValue& x0::FlowValue::set(const x0::IPAddress*) <near match>
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:256:19: note:   no known conversion for argument 1 from ‘uint64_t {aka long long unsigned int}’ to ‘const x0::IPAddress*’
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:264:19: note: x0::FlowValue& x0::FlowValue::set(const char*) <near match>
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:264:19: note:   no known conversion for argument 1 from ‘uint64_t {aka long long unsigned int}’ to ‘const char*’
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:290:19: note: x0::FlowValue& x0::FlowValue::set(const x0::FlowValue&)
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:299:19: note: x0::FlowValue& x0::FlowValue::set(const x0::FlowArray*) <near match>
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:299:19: note:   no known conversion for argument 1 from ‘uint64_t {aka long long unsigned int}’ to ‘const x0::FlowArray*’
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:307:19: note: x0::FlowValue& x0::FlowValue::set(x0::FlowValue::Function) <near match>
/home/unclejack/code/x0/include/x0/flow/FlowValue.h:307:19: note:   no known conversion for argument 1 from ‘uint64_t {aka long long unsigned int}’ to ‘x0::FlowValue::Function {aka bool (*)(void*)}’
```

Fixing these with typecasts leads to further errors:

```
/home/unclejack/code/x0/src/x0d.cpp: In function ‘void crashHandler(int, siginfo_t*, void*)’:
/home/unclejack/code/x0/src/x0d.cpp:1077:77: error: ‘REG_RIP’ was not declared in this scope
```
