### ISSUE TITLE
x0 master doesn't build on 32-bit systems (Ubuntu 12.04)

### ISSUE THREAD

**Issue by unclejack** [christianparpart/x0#50]
Let's try again since #48 was closed and the issue isn't really fixed.

I've written down clang instead of LLVM in #48, but I was really just following the official steps from the README and the INSTALL.

The master doesn't build at all for me using the recommended steps and I have to fix the exact same errors in the source code:

cmake is REALLY using gcc, not clang.

```
git clone https://github.com/xzero/x0.git && cd x0

cmake -DCMAKE_BUILD_TYPE=debug -DLLVM_CONFIG_EXECUTABLE=/usr/bin/llvm-config-3.0 .
OR
cmake -DLLVM_CONFIG_EXECUTABLE=/usr/bin/llvm-config-3.0 .
(same results later on)

make
[  4%] Building CXX object lib/CMakeFiles/XzeroBase.dir/base/Socket.cpp.o
/home/unclejack/code/x0/lib/base/Socket.cpp: In member function ‘virtual ssize_t x0::Socket::read(x0::Buffer&)’:
/home/unclejack/code/x0/lib/base/Socket.cpp:330:81: error: no matching function for call to ‘max(long unsigned int, std::size_t)’
/home/unclejack/code/x0/lib/base/Socket.cpp:330:81: note: candidates are:
/usr/include/c++/4.6/bits/stl_algobase.h:210:5: note: template<class _Tp> const _Tp& std::max(const _Tp&, const _Tp&)
/usr/include/c++/4.6/bits/stl_algobase.h:254:5: note: template<class _Tp, class _Compare> const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
make[2]: *** [lib/CMakeFiles/XzeroBase.dir/base/Socket.cpp.o] Error 1
make[1]: *** [lib/CMakeFiles/XzeroBase.dir/all] Error 2
make: *** [all] Error 2

cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.6/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --enable-targets=all --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.6/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --enable-targets=all --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 

g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.6/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --enable-targets=all --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 

```

Let's verify, MAYBE we're actually using clang without knowing:

```
dpkg -l | grep clang
ii  libclang-common-dev                  3.0-6ubuntu3                                        clang library - Common development package

clang
The program 'clang' is currently not installed.  You can install it by typing:
apt-get install clang
```
